[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
evolution = { path = "../evolution" }
ecology = { path = "../ecology" }
biome = { path = "../biome" }
climate = { path = "../climate" }
geo = { path = "../geo" }
sim-core = { path = "../sim-core" }
sim = { path = "../sim" }
life = { path = "../life" }
observer = { path = "../observer" }
planet = { path = "../planet" }
person = { path = "../person" }
