[package]
name = "person"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
work = { path = "../work" }
sim-core = { path = "../sim-core" }
life = { path = "../life" }
genetics = { path = "../genetics" }
planet = { path = "../planet" }
rand = { workspace = true }
faker_rand = { workspace = true }
