[package]
name = "sim"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sim-core = { path = "../sim-core" }
life = { path = "../life" }
planet = { path = "../planet" }
person = { path = "../person" }
genetics = { path = "../genetics" }
society = { path = "../society" }
economy = { path = "../economy" }
geo = { path = "../geo" }
cosmos = { path = "../cosmos" }
climate = { path = "../climate" }
biome = { path = "../biome" }
settlement = { path = "../settlement" }
culture = { path = "../culture" }
bonds = { path = "../bonds" }

[dev-dependencies]
bonds = { path = "../bonds" }
economy = { path = "../economy" }
